### PR TITLE
escape reges special character

### PR DESCRIPTION
**Pull request by SimonLab**
see [issue 15](https://github.com/dwyl/search-result-keyword-highlighter/issues/15)
@nelsonic do you want to have a look at this PR?

### CODE REVIEW

**Comment by nelsonic** [comment]
Looks good. :+1: 
(_Thanks!_)

**Comment by nelsonic** [comment]
Latest version of the package is on NPM. 
(_but as I understand it, you are not including the module in the App [project](https://github.com/FAC-GM/app/blob/6afa98bae31d0d9d4d91e69a2654cacb2c1b2030/package.json#L24), only the [code](https://github.com/FAC-GM/app/blob/996d61df840f4517c564f29f43f737fd977024ba/assets/js/main.js#L7)...?_)

**Comment by SimonLab** [comment]
Yes @nelsonic, I forget that we don't use the module on the back end of the app. Thanks for that!

**Comment by iteles** [comment]
@SimonLab _Should_ we be using the module to ensure a single codebase to maintain? Do we need to open a technical issue for that?

**Comment by SimonLab** [comment]
@iteles The module highlight text on the backend and for some reason (I need to test it again but I think it was link to the html tags) we can only use a hightlighter on the front-end. We can open an issue/question it will be good to document the reason why we can't use the module (maybe we will find a solution)

**Pull request merged**
